### ISSUE TITLE
Add manual/public Free method

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/gocroaring#12]
https://twitter.com/dgryski/status/981666686741827584

**Comment by Oppen** [comment]
What should happen if I try to operate on a `Free`'d bitmap? `panic`? Or do we just expect the user to write correct code that doesn't attempt that?

**Comment by lemire** [comment]
I think that we expect the users to write correct code. You'd have to go out of your way to write a manual free. You should know what you are doing at that point.

**Comment by Oppen** [comment]
I'm having trouble coming up with an automated test that goes beyond smoke testing. I've been able to corroborate manually freeing reduces peak memory usage compared to relying on finalizers by using the `time` tool, but since the Go `MemStats` only track what the runtime knows about I can't show a thing in the tests themselves.
Any ideas?

**Comment by willglynn** [comment]
Well, here's _an_ idea. Make a test function that `go run`s a subprocess, `syscall.Getrusage()` to measure its RSS? That'd parallelize with the rest of the test harness and would limit the memory measurements to just the code in question.

**Comment by Oppen** [comment]
Cool, I like that.
